use utoipa::OpenApi;

use crate::api::{
    AddSourceRequest, AddSourceResponse, AgentSession, AgentSessionMessageRequest,
    AgentSessionMessageResponse, AgentSessionPollResponse, AgentSessionRegisterRequest,
    DownRequest, ErrorResponse, FacetFilter, FacetValueCount, GcRequest, GcResponse, GlobalSummary,
    GlobalsResponse, HealthStatus, KillRequest, LatestAgentSessionResponse, LogEntry, LogViewQuery,
    LogViewResponse, LogsQuery, LogsResponse, NavigationIntent, NavigationIntentResponse,
    PingResponse, RestartServiceRequest, RunListResponse, RunStatusResponse, RunSummary,
    RunWatchResponse, ServiceStatus, SetNavigationIntentRequest, ShareAgentMessageRequest,
    ShareAgentMessageResponse, SourceSummary, SourcesResponse, StartTaskRequest, StartTaskResponse,
    SystemdStatus, TaskExecutionState, TaskExecutionSummary, TaskStatusResponse, TasksResponse,
    UpRequest, WatchControlRequest, WatchServiceStatus,
};
use crate::manifest::{RunLifecycle, RunManifest, ServiceManifest, ServiceState};

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::daemon::handlers::ping::ping,
        crate::daemon::handlers::agent::register_agent_session,
        crate::daemon::handlers::agent::unregister_agent_session,
        crate::daemon::handlers::agent::post_agent_message,
        crate::daemon::handlers::agent::poll_agent_messages,
        crate::daemon::handlers::agent::get_latest_agent_session,
        crate::daemon::handlers::agent::share_agent_message,
        crate::daemon::handlers::runs::up,
        crate::daemon::handlers::runs::down,
        crate::daemon::handlers::runs::kill,
        crate::daemon::handlers::runs::restart_service,
        crate::daemon::handlers::runs::status,
        crate::daemon::handlers::tasks::start_task,
        crate::daemon::handlers::tasks::task_status,
        crate::daemon::handlers::tasks::run_tasks,
        crate::daemon::handlers::watch::watch_status,
        crate::daemon::handlers::watch::watch_pause,
        crate::daemon::handlers::watch::watch_resume,
        crate::daemon::handlers::logs::logs,
        crate::daemon::handlers::logs::logs_view,
        crate::daemon::handlers::runs::list_runs,
        crate::daemon::handlers::globals::list_globals,
        crate::daemon::handlers::sources::list_sources,
        crate::daemon::handlers::sources::add_source,
        crate::daemon::handlers::sources::remove_source,
        crate::daemon::handlers::sources::source_logs_view,
        crate::daemon::handlers::navigation::set_navigation_intent,
        crate::daemon::handlers::navigation::get_navigation_intent,
        crate::daemon::handlers::navigation::clear_navigation_intent,
        crate::daemon::handlers::gc::gc
    ),
    components(
        schemas(
            UpRequest,
            DownRequest,
            KillRequest,
            RestartServiceRequest,
            WatchControlRequest,
            GcRequest,
            PingResponse,
            AgentSessionRegisterRequest,
            AgentSession,
            AgentSessionMessageRequest,
            AgentSessionMessageResponse,
            AgentSessionPollResponse,
            LatestAgentSessionResponse,
            ShareAgentMessageRequest,
            ShareAgentMessageResponse,
            RunSummary,
            RunListResponse,
            RunManifest,
            ServiceManifest,
            RunStatusResponse,
            StartTaskRequest,
            StartTaskResponse,
            TaskExecutionState,
            TaskStatusResponse,
            TasksResponse,
            TaskExecutionSummary,
            RunWatchResponse,
            ServiceStatus,
            WatchServiceStatus,
            HealthStatus,
            SystemdStatus,
            GlobalsResponse,
            GlobalSummary,
            GcResponse,
            LogsQuery,
            LogsResponse,
            SetNavigationIntentRequest,
            NavigationIntent,
            NavigationIntentResponse,
            LogEntry,
            LogViewQuery,
            FacetValueCount,
            FacetFilter,
            LogViewResponse,
            SourceSummary,
            SourcesResponse,
            AddSourceRequest,
            AddSourceResponse,
            ErrorResponse,
            RunLifecycle,
            ServiceState
        )
    ),
    tags((name = "daemon", description = "Devstack daemon API"))
)]
pub struct ApiDoc;

pub fn openapi() -> utoipa::openapi::OpenApi {
    ApiDoc::openapi()
}
